#+TITLE:     Quiz 5
#+AUTHOR:    Dustin Leatherman
#+OPTIONS: toc:nil

* 1

#+begin_quote
Reggie Jackson hit Y = 10 home runs in N = 27 World Series games. Assume $Y |
\lambda \sim Poisson(N \lambda)$ where $\lambda$ is his World Series home run rate.
#+end_quote


** a

#+begin_quote
The conjugate prior is $\lambda \sim Gamma(a, b)$. Give the posterior under this prior.
#+end_quote

Posterior of Poisson-Gamma: $\lambda | Y \sim Gamma(a + Y, b + N)$

$$
\lambda | Y \sim Gamma(10 + a, 27 + b)
$$

** b

#+begin_quote
The Jeffreys prior is $\pi (\lambda) \propto \lambda^{-1/2}$. Give the posterior
under this prior.
#+end_quote


\begin{equation}
\begin{split}
\lambda | Y \propto & \lambda^Y e^{- \lambda} \cdot \lambda^{-1/2}\\
\propto & \lambda^{Y - 1/2} e^{- \lambda}\\
\propto & \lambda^{(Y + 1/2) - 1} e^{- \lambda}\\
\sim & Gamma(Y + \frac{1}{2}, 1) \sim Gamma(\frac{21}{2}, 1)
\end{split}
\end{equation}

** c

#+begin_quote
Give one situation where you would use the conjugate prior over the Jeffreys
prior. Defend your answer.
#+end_quote

The conjugate prior would be beneficial over the Jeffreys prior if the
number of home runs over the regular season games were known. The parameters a
and b typically represent the prior number of events and the prior observation
time respectively so the conjugate model is more useful to use if this
information is known.

** d

#+begin_quote
Give one situation where you would use the Jeffreys prior over the conjugate
prior. Defend your answer.
#+end_quote

The only parameter in the Posterior derived from Jeffreys Prior is $Y$ which is
known in this case. This is useful to use if there is no prior knowledge to
incorporate into the model and the researcher wants to use an objective prior.

* 2

#+begin_quote
Assume $Y_1, ..., Y_n$ are independent and $Y_1, ..., Y_n | \sigma^2 \sim N(0,
\sigma^2)$. The prior is $\pi (\sigma^2) \propto 1$ for all $\sigma^2 > 0$.
#+end_quote


** a

#+begin_quote
Assuming large n, derive the posterior distribution of $\sigma^2$.
#+end_quote

\begin{equation}
\begin{split}
f(\sigma^2 | Y_1, ..., Y_n) \propto & f(Y_1| \sigma^2) \cdot ... \cdot f(Y_n | \sigma^2) f( \sigma^2)\\
\propto & (\sigma^2)^{- 1/2} e^{- \frac{1}{2 \sigma^2} y_1^2} \cdot ... \cdot  (\sigma^2)^{- 1/2} e^{- \frac{1}{2 \sigma^2} y_n^2} \cdot 1\\
\propto & (\sigma^2)^{-\frac{n}{2}} e^{- \frac{1}{2 \sigma^2} \sum_{i = 1}^{n} y_i^2}\\
\propto & (\sigma^2)^{-(\frac{n}{2} - 1) - 1} e^{- \frac{1}{2 \sigma^2} \sum_{i = 1}^{n} y_i^2}\\
\sim & InvGamma(\frac{n}{2} - 1, \frac{1}{2} \sum_{i = 1}^{n} y_i^2)
\end{split}
\end{equation}

** b

#+begin_quote
Give a value of n so that for all n at least as large as this value, the
posterior in (a) is guaranteed to be a proper distribution. Defend your answer.
#+end_quote

To be a proper Gamma and Inverse Gamma distribution, the parameters a and b must
both be positive. Since a is the only parameter using n, it is the only one that
needs to be considered when determining a lower bound for n.


\begin{equation}
\begin{split}
\frac{n}{2} - 1 > & 0\\
\frac{n}{2} > & 1\\
n > & 2
\end{split}
\end{equation}

For all n > 2, the Posterior distribution will be valid.
