#+TITLE:     Optimization - Homework 1
#+AUTHOR:    Dustin Leatherman

* Problem Statement

Let
$$
A = \begin{bmatrix} 3 & 1 & 4 & 1 & 5 & 9 & 2 & 6\\ 2 & 7 & 1 & 8 & 2 & 8 &
1 & 8\\ 1 & 4 & 1 & 4 & 2 & 1 & 3 & 5 \end{bmatrix} , \vec{y} = \begin{bmatrix}
-7\\ 20\\ 8
\end{bmatrix}
$$


Find a 2-Space Vector $\vec{x} \in \R^8$ so that $\vec{y} = A \vec x$

At least one of the following vectors are a solution:

$$
\vec{x_1} = \begin{bmatrix}
0\\ 0\\ 0\\ 0\\ a\\ b\\ 0\\ 0
\end{bmatrix}, \ \vec{x_2} = \begin{bmatrix}
a\\ b\\ 0\\ 0\\ 0\\ 0\\ 0\\ 0
\end{bmatrix}, \ \vec{x_3} = \begin{bmatrix}
0\\ 0\\ 0\\ a\\ b\\ 0\\ 0\\ 0
\end{bmatrix}, \ \vec{x_4} = \begin{bmatrix}
0\\ 0\\ 0\\ 0\\ 0\\ 0\\ a\\ b
\end{bmatrix}
$$

There are ${8 \choose 2} = 28$ 2-sparse vectors but only the four need to be considered.

* Solution

** Guiding Principles
$\vec y = A \vec x$ where $\vec x$ contains free variables produces a system of
equations which can be organized into a matrix R. Row reduction is applied to
R to obtain discrete values $a', \ b'$ for the free variables. $a', \ b'$ are
then tested using the remaining equation. If the equation is valid, then $x_i$ is a valid solution. Otherwise,
it is not.

** $\mbox{\Large x_1}$
*** Organize $\vec y = A x_1$ into a System of equations.
\begin{equation}
\begin{split}
\vec y = A x_1 & \\
\to & \begin{bmatrix} -7\\ 20\\ 8 \end{bmatrix} = \begin{bmatrix} 3 & 1 & 4 & 1 & 5 & 9 & 2 & 6\\ 2 & 7 & 1 & 8 & 2 & 8 &
1 & 8\\ 1 & 4 & 1 & 4 & 2 & 1 & 3 & 5 \end{bmatrix} \begin{bmatrix}
0\\ 0\\ 0\\ 0\\ a\\ b\\ 0\\ 0
\end{bmatrix}\\
\to & \begin{bmatrix}
-7\\ 20\\ 8
\end{bmatrix} = \begin{bmatrix}
5a + 9b\\
2a + 8b\\
2a + b
\end{bmatrix}\\
\to & \begin{bmatrix}
5 & 9 & -7\\
2 & 8 & 20\\
2 & 1 & 8
\end{bmatrix} \begin{bmatrix}
a\\ b\\ 1
\end{bmatrix}
\end{split}
\end{equation}

*** Apply Row Reduction to solve free variables.

\begin{equation}
\begin{split}
\begin{bmatrix}
5 & 9 & -7\\
2 & 8 & 20\\
2 & 1 & 8
\end{bmatrix} \underset{-r_3 + r_2}{\to}
\begin{bmatrix}
5 & 9 & -7\\
0 & 7 & 12\\
2 & 1 & 8
\end{bmatrix} \underset{-9r_3 + r_1}{\to}
\begin{bmatrix}
-13 & 0 & -79\\
0 & 7 & 12\\
2 & 1 & 8
\end{bmatrix}
\end{split}
\end{equation}


\begin{subequations}
\label{eq:Dustin}
\begin{equation}
-13a + 0 = & -79\\
\end{equation}
\begin{equation}
7b + 0 = & 12\\
\end{equation}
\begin{equation}
2a + b = & 8
\end{equation}
\end{subequations}

Solving for $a',b'$ using (3a) and (3b) yields $a' = \frac{79}{13}, \ b' =
\frac{12}{7}$

*** Plug values into the remaining equation

   Replacing $a', \ b'$ in (3c) yields $2(\frac{79}{13} + \frac{12}{7} \neq 8)$.
   Thus $\vec x_1$ is *not* a valid solution

** $\mbox{\Large x_2}$
*** Organize $\vec y = A x_2$ into a System of equations.
\begin{equation}
\begin{split}
\vec y = A x_2 & \\
\to & \begin{bmatrix} -7\\ 20\\ 8 \end{bmatrix} = \begin{bmatrix} 3 & 1 & 4 & 1 & 5 & 9 & 2 & 6\\ 2 & 7 & 1 & 8 & 2 & 8 &
1 & 8\\ 1 & 4 & 1 & 4 & 2 & 1 & 3 & 5 \end{bmatrix} \begin{bmatrix}
a\\ b\\ 0\\ 0\\ 0\\ 0\\ 0\\ 0
\end{bmatrix}\\
\to & \begin{bmatrix}
-7\\ 20\\ 8
\end{bmatrix} = \begin{bmatrix}
3a + b\\
2a + 7b\\
a + 4b
\end{bmatrix}\\
\to & \begin{bmatrix}
3 & 1 & -7\\
2 & 7 & 20\\
1 & 4 & 8
\end{bmatrix} \begin{bmatrix}
a\\ b\\ 1
\end{bmatrix}
\end{split}
\end{equation}

*** Apply Row Reduction to solve free variables.

\begin{equation}
\begin{split}
\begin{bmatrix}
3 & 1 & -7\\
2 & 7 & 20\\
1 & 4 & 8
\end{bmatrix} \underset{-2r_3 + r_2}{\to}
\begin{bmatrix}
3 & 1 & -7\\
0 & -1 & 4\\
1 & 4 & 8
\end{bmatrix} \underset{-4r_2 + r_3}{\to}
\begin{bmatrix}
3 & 1 & -7\\
0 & -1 & 4\\
1 & 0 & 24
\end{bmatrix}
\end{split}
\end{equation}


\begin{subequations}
\label{eq:Dustin}
\begin{equation}
3a + b = & -7\\
\end{equation}
\begin{equation}
0 + -b = & 4\\
\end{equation}
\begin{equation}
a + 0 = & 24
\end{equation}
\end{subequations}

Solving for $a', \ b'$ using (6b) and (6c) yields $a' = 24, \ b' = -4$

*** Plug values into the remaining equation

   Replacing $a', \ b'$ in (6a) yields $3(24) - 4 \neq 7)$.
   Thus $\vec x_2$ is *not* a valid solution
** $\mbox{\Large x_3}$

*** Organize $\vec y = A x_3$ into a System of equations.
\begin{equation}
\begin{split}
\vec y = A x_3 & \\
\to & \begin{bmatrix} -7\\ 20\\ 8 \end{bmatrix} = \begin{bmatrix} 3 & 1 & 4 & 1 & 5 & 9 & 2 & 6\\ 2 & 7 & 1 & 8 & 2 & 8 &
1 & 8\\ 1 & 4 & 1 & 4 & 2 & 1 & 3 & 5 \end{bmatrix} \begin{bmatrix}
0\\ 0\\ 0\\ a\\ b\\ 0\\ 0\\ 0
\end{bmatrix}\\
\to & \begin{bmatrix}
-7\\ 20\\ 8
\end{bmatrix} = \begin{bmatrix}
a + 5b\\
8a + 2b\\
4a + 2b
\end{bmatrix}\\
\to & \begin{bmatrix}
1 & 5 & -7\\
8 & 2 & 20\\
4 & 2 & 8
\end{bmatrix} \begin{bmatrix}
a\\ b\\ 1
\end{bmatrix}
\end{split}
\end{equation}

*** Apply Row Reduction to solve free variables.

\begin{equation}
\begin{split}
\begin{bmatrix}
1 & 5 & -7\\
8 & 2 & 20\\
4 & 2 & 8
\end{bmatrix} \underset{-2r_3 + r_2}{\to}
\begin{bmatrix}
1 & 5 & -7\\
0 & -2 & 4\\
4 & 2 & 8
\end{bmatrix} \underset{r_2 + r_3}{\to}
\begin{bmatrix}
1 & 5 & -7\\
0 & -2 & 4\\
4 & 0 & 12
\end{bmatrix} \underset{\frac{1}{4}r_3, -\frac{1}{2} r_2}{\to}
\begin{bmatrix}
1 & 5 & -7\\
0 & 1 & -2\\
1 & 0 & 3
\end{bmatrix}
\end{split}
\end{equation}


\begin{subequations}
\label{eq:Dustin}
\begin{equation}
a + 5b = & -7\\
\end{equation}
\begin{equation}
0 + b = & -2\\
\end{equation}
\begin{equation}
a + 0 = & 3
\end{equation}
\end{subequations}

Solving for $a', \ b'$ using (9b) and (9c) yields $a' = 3, \ b' = -2$

*** Plug values into the remaining equation

   Replacing $a', \ b'$ in (9a) yields $3 + 5(-2) = -7$.
   Thus $\vec x_3$ *is* a valid solution
** $\mbox{\Large x_4}$

*** Organize $\vec y = A x_4$ into a System of equations.
  
\begin{equation}
\begin{split}
\vec y = A x_4 & \\
\to & \begin{bmatrix} -7\\ 20\\ 8 \end{bmatrix} = \begin{bmatrix} 3 & 1 & 4 & 1 & 5 & 9 & 2 & 6\\ 2 & 7 & 1 & 8 & 2 & 8 &
1 & 8\\ 1 & 4 & 1 & 4 & 2 & 1 & 3 & 5 \end{bmatrix} \begin{bmatrix}
0\\ 0\\ 0\\ 0\\ 0\\ 0\\ a\\ b
\end{bmatrix}\\
\to & \begin{bmatrix}
-7\\ 20\\ 8
\end{bmatrix} = \begin{bmatrix}
2a + 6b\\
a + 8b\\
3a + 5b
\end{bmatrix}\\
\to & \begin{bmatrix}
2 & 6 & -7\\
1 & 8 & 20\\
3 & 5 & 8
\end{bmatrix} \begin{bmatrix}
a\\ b\\ 1
\end{bmatrix}
\end{split}
\end{equation}

*** Apply Row Reduction to solve free variables.

\begin{equation}
\begin{split}
\begin{bmatrix}
2 & 6 & -7\\
1 & 8 & 20\\
3 & 5 & 8
\end{bmatrix} \underset{-3r_2 + r_3}{\to}
\begin{bmatrix}
2 & 6 & -7\\
1 & 8 & 20\\
0 & -19 & -52
\end{bmatrix} \underset{- \frac{8}{19} r_3 + r_2}{\to}
\begin{bmatrix}
2 & 6 & -7\\
1 & 0 & \frac{160}{19}\\
0 & -19 & -52
\end{bmatrix}
\end{split}
\end{equation}


\begin{subequations}
\label{eq:Dustin}
\begin{equation}
2a + 6b = & -7\\
\end{equation}
\begin{equation}
a + 0 = & \frac{160}{19}\\
\end{equation}
\begin{equation}
0 - 19b = & -52
\end{equation}
\end{subequations}

Solving for $a', \ b'$ using (12b) and (12c) yields $a' = \frac{160}{19}, \ b' = \frac{52}{19}$

*** Plug values into the remaining equation

   Replacing $a', \ b'$ in (12a) yields $2(\frac{160}{19}) + 6(\frac{52}{19}) = -7$.
   Thus $\vec x_4$ is *not* a valid solution
