#+TITLE:     Homework #3
#+AUTHOR:    Dustin Leatherman


* 1
** a
#+begin_quote
Estimate the dispersion parameter.
#+end_quote
For Binomial or Poisson distributions, the dispersion parameter can be estimated
by the /Pearson Chi-Squared Statistic/

\begin{equation}
\begin{split}
\hat \phi = \frac{X^2}{n - p} = 1.2927
\end{split}
\end{equation}

** b
#+begin_quote
Compute Full Log Likelihood and BIC for the model (hint AIC is given)
#+end_quote

\begin{equation}
\begin{split}
AIC = & -2 l(\hat \pi; y) + 2p\\
BIC = & -2 l(\hat \pi; y) + p \times log(n)
\end{split}
\end{equation}

*Log Likelihood*

\begin{equation}
\begin{split}
92.2094 = & -2 \ l(\hat \pi ; y) + 2p\\
46.1047 = &  - l(\hat \pi; y) + 2\\
-44.1047 = & l(\hat \pi; y)
\end{split}
\end{equation}

*BIC*

\begin{equation}
\begin{split}
-44.1047 \times -2 + 2 \times log(22) = 94.39148
\end{split}
\end{equation}
* 2
#+begin_quote
Let Y = number of ACFs in the rat colons and x = sacrificed times (endtime, 6,
12, and 18). Compute the predicted probabilities for Y = 2, 4, 8, and x = 12.


#+end_quote


\begin{equation}
\begin{split}
\lambda = & exp(-0.3215 + 0.1192 \times 12) = 3.031022\\
P(y) = & \frac{e^{- \lambda} \lambda^y}{y!}\\
= & \frac{e^{- 3.031022} 3.031022^y}{y!}\\
\end{split}
\end{equation}

|   | Y | P(y/ x = 12) |
|---+---+--------------|
| 1 | 2 |    0.2217134 |
| 2 | 4 |    0.1697419 |
| 3 | 8 |    0.0085278 |
** a
#+begin_quote
How do we interpret $\hat \beta_1 = 0.1192$?
#+end_quote

\begin{equation}
\begin{split}
exp(0.1192) = 1.126595
\end{split}
\end{equation}

The incident rate ratio increases by 120% for each one-unit increase in
sacrifice time.

* 3
#+begin_quote
To study factors that affect the recurrence of heart attacks (HA), an
investigator collected data from 20 HA victims. The investigator fit a logistic regression model with an indicator of a second
HA within one year (1 = HA; 0 = no HA) as the binary outcome. There are two
predictors: $x_1 = 1$ if the patient completed an anger management program; 0
else. $x_2 =$ anxiety score (0 = low, 100 = high). Computer output is given
below:

|           | Estimate | Std Err | Z value | P Value |
|-----------+----------+---------+---------+---------|
| Intercept |    -6.36 |    3.21 |   -1.98 |    0.05 |
| X1        |    -1.02 |    1.17 |   -0.88 |    0.38 |
| X2        |     0.12 |    0.06 |    2.17 |    0.03 |
#+end_quote

** a
#+begin_quote
In terms of $x_1$ and $x_2$, what are the odds of a patient having a second
heart attack?
#+end_quote

\begin{equation}
\begin{split}
\omega_{AB} = & \frac{\omega_A}{\omega_B}\\
= & \frac{e^{X0 + X1 \times 1 + X2 \times A}}{e^{X0 + X1 \times 0 + X2 \times B}}\\
= & e^{X1 (1 - 0) + X2(A = B)}\\
= & e^{X1 + X2 (A - B)}
\end{split}
\end{equation}

** b
#+begin_quote
What is the probability of a second heart attack for a patient that has
completed an anger management program and scored a 100 on the anxiety test?
#+end_quote

\begin{equation}
\begin{split}
\pi = & \frac{e^\eta}{1 + e^\eta}\\
= & \frac{e^{-6.36 - 1.02 \times 1 + 0.12 \times 100}}{1 + e^{-6.36 - 1.02 \times 1 + 0.12 \times 100}}\\
= & 0.9902433
\end{split}
\end{equation}


** c
#+begin_quote
For patients that have completed the anger management program, is high anxiety
associated with an increased probability of a second heart attack?
#+end_quote

Regardless of whether or not a patient has completed the anger management
program, there is moderate evidence that a higher anxiety score is associated with an
increased risk of a second heart attack (p-value = 0.03).

** d
#+begin_quote
Is there statistical evidence that an anger management program is associated
with a reduction in the probability of a second heart attack? Explain.
#+end_quote

There is no evidence that completion of the anger management program is
associated with reduced probability of a second heart attack (p-value = 0.38).
The confidence interval for the anger management predictor encompasses 0
indicating that there is no conclusive effect on the estimated predicted probability.

** e
#+begin_quote
Explain why linear regression is in appropriate for modeling the probability of
a second heart attack.
#+end_quote

Linear Regression may yield invalid values, in this case, an estimated
probability using Linear Regression may be outside the interval of $[0,1]$.
Linear Regression could be used to estimate a relative score or value that could
be interpreted in a similar fashion but there would be no guarantee on the range
of scores that would occur; whereas when modeling probabilities, the probability
is guaranteed to be between 0 and 1.

* 4
#+begin_quote
Let Y be a binomial distribution. Show taht Y has the exponential distribution
of the form:

$$
f(y; \theta) = s(y) y(\theta) exp(a(y) b(\theta));
$$

this can be rewritten

$$
f(y; \theta) = exp(a(y) (\theta) + c(\theta) + d(y))
$$
#+end_quote


** a
#+begin_quote
Clearly identify the link function, $b(\theta)$
#+end_quote

\begin{equation}
\begin{split}
f(y; \pi) = & {n \choose y} \pi^y (1 - \pi)^{n - y}\\
= & exp(y \ log(\pi) + (n - y) log(1 - \pi) + log({n \choose y}))\\
= & exp(y \ log (\pi) + n \ log(1 - \pi) - y \ log(1 - \pi) + log({n \choose y}))\\
= & exp(y \ (log(\pi) - log(1 - \pi)) + n \ log (1 - \pi) + log({n \choose y}))\\
= & exp(y \ log(\frac{\pi}{1 - \pi}) + n \ log (1 - \pi) + log({n \choose y}))\\
\end{split}
\end{equation}

$a(y) = y$

$b(\theta) = log(\frac{\pi}{1 - \pi})$

$c(\theta) = n log(1 - \pi)$

$d(y) = log({n \choose y})$

* 5
#+begin_quote
For games in baseball's National League during nine decades: The following table
shows the percentage of times that the starting pitcher pitched a complete game.

|   | Decade_complete | Percent |
|---+-----------------+---------|
| 1 |       1900-1909 |    72.7 |
| 2 |       1910-1919 |    63.4 |
| 3 |       1920-1939 |      50 |
| 4 |       1930-1939 |    44.3 |
| 5 |       1940-1949 |    41.6 |
| 6 |       1950-1959 |    32.8 |
| 7 |       1960-1969 |    27.2 |
| 8 |       1970-1979 |    22.5 |
| 9 |       1980-1989 |    13.3 |

#+end_quote

** a
#+begin_quote
Treating the number of games as the same in each decade, the ML fit of the
linear probability model is $\hat p = 0.7578 - 0.0694 x$, where x = decade
[1:9]. Interpret
#+end_quote

Each additional decade starting at 1900 is associated with a 6.94% /decrease/ in
the percentage of times that the starting pitcher pitched a complete game.

** b
#+begin_quote
Substituting $x = 10,11,12$, predict the percentage of complete games for the
next three decades. Are these predictions plausible? Why?
#+end_quote

\begin{equation}
\begin{split}
0.7578 - 0.0694 \times 11 = & -0.0056\\
0.7578 - 0.0694 \times 12 = & -0.075\\
0.7578 - 0.0694 \times 13 = & -0.1444\\
\end{split}
\end{equation}

These predictions are not plausible because they fall outside the range between
0 and 1. This is one of the reasons why linear regression is not suitable for
predicting probabilities.

** c
#+begin_quote
The ML Fit with logistic regression is

$$
\hat p = exp(1.148 - 0.315 x) /(1 + exp(1.148 - 0.315 x))
$$

Obtain for $x = 10,11,12$. Are these more plausible?
#+end_quote

\begin{equation}
\begin{split}
exp(1.148 - 0.315 \times 10) /(1 + exp(1.148 - 0.315 \times 10)) = & \ 0.1189931\\
exp(1.148 - 0.315 \times 11) /(1 + exp(1.148 - 0.315 \times 11)) = & \ 0.08972478\\
exp(1.148 - 0.315 \times 12) /(1 + exp(1.148 - 0.315 \times 12)) = & \ 0.06710713\\
\end{split}
\end{equation}

These are more plausible since the values are valid (between 0 and 1) and still show a
decreasing probability over time.

* 6
#+begin_quote
Show that the following probability density functions belong to the exponential family:
#+end_quote

** a
#+begin_quote
Pareto distribution

$$
f(y: \theta) = \thetaY^{-\theta-1}
$$
#+end_quote

\begin{equation}
\begin{split}
f(y; \theta) = & \ \theta Y^{-\theta - 1}\\
= & \ exp((- \theta - 1) \ log(y) + log(\theta))\\
= & \ exp(- \theta log(y) - log(y) + log(\theta))
\end{split}
\end{equation}


\begin{equation}
\begin{split}
a(y) = & \ - log(y)\\
b(\theta) = & \ \theta\\
c(\theta) = & \ log(\theta)\\
d(y) = & \ - log(y)
\end{split}
\end{equation}

** b
#+begin_quote
Exponential distribution

$$
f(y; \theta) = \theta \ exp(-y \theta)
$$
#+end_quote

\begin{equation}
\begin{split}
f(y; \theta) = & \ \theta \ exp(-y \theta)\\
= & \ exp(log(\theta) - y \theta)
\end{split}
\end{equation}


\begin{equation}
\begin{split}
a(y) = & \ -y\\
b(\theta) = & \ \theta\\
c(\theta) = & \ log(\theta)\\
d(y) = & \ 0
\end{split}
\end{equation}

* 7
#+begin_quote
The following associations can be described by generalized linear models. For
each one:
1. Identify the response variable and the explanatory variables
2. Select a probability distribution for the response (justifying your choice)
3. Write down the linear component
#+end_quote

** a
#+begin_quote
The effect of age, sex, height, mean daily food intake, and mean daily energy
expenditure on a person's weight.
#+end_quote

1. A person's weight.
2. t-distribution since weight is a nominal value with no inherent limitations
   in terms of range of values.
3. $\hat{weight} = \beta_0 + \beta_1 \ age + \beta_2 \ isMale + \beta_3 \ height + \beta_4 \ avgDailyFoodIntake + \beta_5 \ avgDailyEnergyExpend$

** b
#+begin_quote
The proportion of laboratory mice that become infected after exposure to
bacteria when five different exposure levels are used and 20 mice are exposed at
each level.
#+end_quote

1. Proportion of infected laboratory mice
2. Binomial Distribution since a mouse can either be infected or not infected.
3. $\hat{infected} = \beta_0 + \beta_1 \ exp1 + \beta_2 \ exp2 + \beta_3 \
   exp3 + \beta_4 \ exp4 + \beta_5 \ exp5$ where exp1 through exp5 are indicator variables (1 when exposed at a given level; 0 otherwise).

** c
#+begin_quote
The association between the number of trips per week to the supermarket for a
household and the number of people in the household, the household income, and
the distance of the supermarket.
#+end_quote

1. The number of trips per week to the supermarket.
2. Poisson or Negative Binomial Distribution. If a Poisson model is fit and
   there is over-dispersion, then a Negative Binomial Distribution may be a
   better fit. Both Poisson and Negative Binomial are useful distributions for
   modeling /count/ data, which this response variable is.
3. $\hat{tripsPerWeek} = \beta_0 + \beta_1 \ numPeople + \beta_2 \ income + \beta_3 \ distance$
